# To be used with `docker-compose`. Start with `docker-compose up`
# This is not meant for production use. Just a quick developer setup.
version: '2'

services:
    db:
        image: postgres:9.4
        volumes:
            - ./docker_volumes/db:/var/lib/postgresql/data:rw
        environment:
            - POSTGRES_PASSWORD=paws
            - POSTGRES_USER=paws
    web:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./docker_volumes/logs:/srv/pawsnyc/logs:rw
        links:
            - db
            #- cache
        environment:
            - DJANGO_SETTINGS_MODULE=charityadmin.settings
            - DJANGO_SECRET_KEY=a@62gb!m1f3(79-hx*7oa1nnmu+tp)__e=_afh#o=eia%&gi@t
            - DATABASE_URL=postgres://paws@db:5432/paws \
            - DJANGO_CONFIGURATION=Dev
        #    - CACHE_URL=memcached://cache:11211
