# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 17:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, choices=[(b'AL', 'Alabama'), (b'AK', 'Alaska'), (b'AS', 'American Samoa'), (b'AZ', 'Arizona'), (b'AR', 'Arkansas'), (b'AA', 'Armed Forces Americas'), (b'AE', 'Armed Forces Europe'), (b'AP', 'Armed Forces Pacific'), (b'CA', 'California'), (b'CO', 'Colorado'), (b'CT', 'Connecticut'), (b'DE', 'Delaware'), (b'DC', 'District of Columbia'), (b'FL', 'Florida'), (b'GA', 'Georgia'), (b'GU', 'Guam'), (b'HI', 'Hawaii'), (b'ID', 'Idaho'), (b'IL', 'Illinois'), (b'IN', 'Indiana'), (b'IA', 'Iowa'), (b'KS', 'Kansas'), (b'KY', 'Kentucky'), (b'LA', 'Louisiana'), (b'ME', 'Maine'), (b'MD', 'Maryland'), (b'MA', 'Massachusetts'), (b'MI', 'Michigan'), (b'MN', 'Minnesota'), (b'MS', 'Mississippi'), (b'MO', 'Missouri'), (b'MT', 'Montana'), (b'NE', 'Nebraska'), (b'NV', 'Nevada'), (b'NH', 'New Hampshire'), (b'NJ', 'New Jersey'), (b'NM', 'New Mexico'), (b'NY', 'New York'), (b'NC', 'North Carolina'), (b'ND', 'North Dakota'), (b'MP', 'Northern Mariana Islands'), (b'OH', 'Ohio'), (b'OK', 'Oklahoma'), (b'OR', 'Oregon'), (b'PA', 'Pennsylvania'), (b'PR', 'Puerto Rico'), (b'RI', 'Rhode Island'), (b'SC', 'South Carolina'), (b'SD', 'South Dakota'), (b'TN', 'Tennessee'), (b'TX', 'Texas'), (b'UT', 'Utah'), (b'VT', 'Vermont'), (b'VI', 'Virgin Islands'), (b'VA', 'Virginia'), (b'WA', 'Washington'), (b'WV', 'West Virginia'), (b'WI', 'Wisconsin'), (b'WY', 'Wyoming')], max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(db_column=b'userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(default=datetime.datetime(2016, 6, 14, 12, 0, tzinfo=utc), verbose_name=b'Start Date')),
                ('endDate', models.DateTimeField(blank=True, null=True, verbose_name=b'End Date')),
                ('type', models.CharField(choices=[(b'One-Off', b'One-Off'), (b'Days of Week', b'Days of Week'), (b'Days of Alt Week', b'Days of Alternating Week'), (b'Day of Month', b'Day of Month')], default=b'Days of Week', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(db_column=b'clientId', on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='timeslots.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOpeningException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=b'Exception Date')),
                ('clientOpening', models.ForeignKey(db_column=b'clientOpeningId', on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='timeslots.ClientOpening')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOpeningMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.CharField(max_length=20)),
                ('clientOpening', models.ForeignKey(db_column=b'clientOpeningId', on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='timeslots.ClientOpening')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('clients', models.ManyToManyField(blank=True, to='timeslots.Client')),
                ('user', models.OneToOneField(db_column=b'userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerCommitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'Start Date')),
                ('endDate', models.DateTimeField(blank=True, null=True, verbose_name=b'End Date')),
                ('type', models.CharField(choices=[(b'One-Off', b'One-Off'), (b'Days of Week', b'Days of Week'), (b'Days of Alt Week', b'Days of Alternating Week'), (b'Day of Month', b'Day of Month')], default=b'Days of Week', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('clientOpening', models.ForeignKey(db_column=b'clientOpeningId', on_delete=django.db.models.deletion.CASCADE, to='timeslots.ClientOpening')),
                ('volunteer', models.ForeignKey(db_column=b'volunteerId', on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='timeslots.Volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerCommitmentException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=b'Exception Date')),
                ('volunteerCommitment', models.ForeignKey(db_column=b'volunteerCommitmentId', on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='timeslots.VolunteerCommitment')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerCommitmentMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.CharField(max_length=20)),
                ('volunteerCommitment', models.ForeignKey(db_column=b'volunteerCommitmentId', on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='timeslots.VolunteerCommitment')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to='timeslots.Volunteer'),
        ),
    ]
